### ISSUE TITLE
Unable to find module 'fido'

### ISSUE THREAD

**Issue by pepa65** [r4gus/passkee#1]
I corrected the hash, but then after `zig build`:
```
thread 1827022 panic: unable to find module 'fido'
/opt/zig/lib/std/debug.zig:374:22: 0x388209 in panicExtra__anon_47153 (build)
    std.builtin.panic(msg, trace, ret_addr);
                     ^
/opt/zig/lib/std/debug.zig:349:15: 0x360679 in panic__anon_28785 (build)
    panicExtra(null, null, format, args);
              ^
/opt/zig/lib/std/Build.zig:1556:18: 0x335bf7 in module (build)
            panic("unable to find module '{s}'", .{name});
                 ^
/data/git/passkee/build.zig:29:43: 0x2f0a5d in build (build)
    exe.addModule("fido", fido2_dep.module("fido"));
                                          ^
/opt/zig/lib/std/Build.zig:1638:33: 0x2df9c3 in runBuild__anon_7135 (build)
        .Void => build_zig.build(b),
                                ^
/opt/zig/lib/build_runner.zig:297:29: 0x2db6b1 in main (build)
        try builder.runBuild(root);
                            ^
/opt/zig/lib/std/start.zig:574:37: 0x2c6eee in posixCallMainAndExit (build)
            const result = root.main() catch |err| {
                                    ^
/opt/zig/lib/std/start.zig:243:5: 0x2c69d1 in _start (build)
    asm volatile (switch (native_arch) {
    ^
???:?:?: 0x4 in ??? (???)
Unwind information for `???:0x4` was not available, trace may be incomplete

error: the following build command crashed:
/data/git/passkee/zig-cache/o/137b5c6acb813b0982f87c7270630a8b/build /opt/zig/zig /data/git/passkee /data/git/passkee/zig-cache /home/pp/.cache/zig
```

**Comment by r4gus** [comment]
Please check out this other [repo](https://github.com/r4gus/scallop/blob/main/platform-auth/main.zig). The platform-auth folder contains a working example for Linux (you might run into problems with libnotify, e.g. pkg-config cant find the library.).

**Comment by pepa65** [comment]
I copied that `main.zig` file from `scallop/platform-auth` to `src/scallop` and then did `zig build-exe src/scallop.zig`. I get this:
```
src/scallop.zig:8:16: error: C import failed
const notify = @cImport({
               ^~~~~~~~
src/scallop.zig:8:16: note: libc headers not available; compilation does not link against libc
referenced by:
    main: src/scallop.zig:142:24
    callMain: /opt/zig/lib/std/start.zig:574:32
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
/data/git/passkee/zig-cache/o/abd09daeac344d879d1cb97dfffb9876/cimport.h:1:10: error: 'libnotify/notify.h' file not found
#include <libnotify/notify.h>
         ^
```

The file `/usr/include/libnotify/notify.h` is present...

**Comment by r4gus** [comment]
This seems to be an issue with libnotify (I tried libnotify, libnotify-dev, libnotify4) but you can try to install it with homebrew `brew install libnotify`. That fixed it for me.

**Comment by pepa65** [comment]
I have `libnotify-dev` installed which has:
```
/usr
/usr/include
/usr/include/libnotify
/usr/include/libnotify/notification.h
/usr/include/libnotify/notify-enum-types.h
/usr/include/libnotify/notify-features.h
/usr/include/libnotify/notify.h
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/libnotify.pc
/usr/share
/usr/share/doc
/usr/share/doc/libnotify-dev
/usr/share/doc/libnotify-dev/copyright
/usr/share/gir-1.0
/usr/share/gir-1.0/Notify-0.7.gir
/usr/lib/x86_64-linux-gnu/libnotify.so
/usr/share/doc/libnotify-dev/changelog.Debian.gz
```

I also have `libnotify-bin` and `libnotify4`.
I don't have `brew`... But it must be more an issue of zig not finding the file. Is there a way to tell zig where to look?

**Comment by r4gus** [comment]
Zig uses pkg-config. You can try to run pkg-config with libnotify. If nothing shows up running pkg-config, zig build will also fail. This is for example my output: 
```
pkg-config --cflags libnotify
-pthread -I/home/linuxbrew/.linuxbrew/Cellar/libffi/3.4.4/include -I/home/linuxbrew/.linuxbrew/Cellar/libnotify/0.8.2/include -I/home/linuxbrew/.linuxbrew/Cellar/gdk-pixbuf/2.42.10_1/include/gdk-pixbuf-2.0 -I/home/linuxbrew/.linuxbrew/opt/libpng/include/libpng16 -I/home/linuxbrew/.linuxbrew/Cellar/libtiff/4.5.1/include -I/home/linuxbrew/.linuxbrew/opt/zstd/include -I/home/linuxbrew/.linuxbrew/Cellar/xz/5.4.4/include -I/home/linuxbrew/.linuxbrew/Cellar/jpeg-turbo/3.0.0/include -I/home/linuxbrew/.linuxbrew/Cellar/glib/2.76.5/include -I/home/linuxbrew/.linuxbrew/opt/zlib/include -I/home/linuxbrew/.linuxbrew/Cellar/util-linux/2.39.2/include/libmount -I/home/linuxbrew/.linuxbrew/Cellar/util-linux/2.39.2/include/blkid -I/home/linuxbrew/.linuxbrew/Cellar/glib/2.76.5/include -I/home/linuxbrew/.linuxbrew/Cellar/glib/2.76.5/include/glib-2.0 -I/home/linuxbrew/.linuxbrew/Cellar/glib/2.76.5/lib/glib-2.0/include -I/home/linuxbrew/.linuxbrew/Cellar/pcre2/10.42/include
```
Seems like the apt packages don't update the registry.

**Comment by pepa65** [comment]
If I do `pkg-config --cflags libnotify` I get:
```
-pthread -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/x86_64-linux-gnu -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
```

... which looks good to me. I just don't know how to properly include them in the `zig build-exe` commandline.

**Comment by r4gus** [comment]
If you have libnotify installed and just want to build the example run `build zig auth` within to root dir (pull the latest commit before). If you want to use it as a module I'd suggest you create a new project with `zig init-ext` create a `build.zig.zon` e.g.

```zon
.{
    .name = "your-project",
    .version = 0.0.1,

    .dependencies = .{
        .scallop = .{
            .url = "https://github.com/r4gus/scallop/archive/main.tar.gz",
            .hash = "122036646fd5c72c265f2eb4dfc4b9891696a38e7c614b234b3ea65795eb2584d052",
        }
    },
}
```
Remember to update the hash! And then add the module to your app.

**Comment by pepa65** [comment]
The only thing I want is to be able to run something that will act as a soft-authenticator client. I lack the skills in zig to make my own app for that. I was hoping `passkee` would do that.

**Comment by r4gus** [comment]
There is a alpha release available (https://github.com/r4gus/scallop/releases/tag/0.1.0-alpha). If you have a debian based distro, you can use the `.deb` package. Otherwise you have to do the system config manually (https://github.com/r4gus/scallop/tree/main/platform-auth#system-configuration)

**Comment by pepa65** [comment]
Thank you for going out of your way to help. I don't really want to run a database etc. On my home-laptop I use https://github.com/psanford/tpm-fido and that works great, but it doesn't work on my work-laptop somehow, so I am looking for a software fido solution (no USB stick, and no TPM) to achieve the same result. If it is not locked to a laptop's TPM, but to a key that I can transfer to other devices, even better.

**Comment by r4gus** [comment]
I think what you want is one of the password managers with Fido2 support. I think 1Password for example released fido support recently but I dont know for which operating systems. I also would advice against using the example code for storing real credentials, mainly because I'm still experimenting with the overall interface. I'm currently rewriting the core.
